%%
%% %CopyrightBegin%
%%
%% SPDX-License-Identifier: Apache-2.0
%%
%% Copyright Ericsson AB 2009-2025. All Rights Reserved.
%%
%% Licensed under the Apache License, Version 2.0 (the "License");
%% you may not use this file except in compliance with the License.
%% You may obtain a copy of the License at
%%
%%     http://www.apache.org/licenses/LICENSE-2.0
%%
%% Unless required by applicable law or agreed to in writing, software
%% distributed under the License is distributed on an "AS IS" BASIS,
%% WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
%% See the License for the specific language governing permissions and
%% limitations under the License.
%%
%% %CopyrightEnd%
%%

%%%-------------------------------------------------------------------
%%% File: ct_html_validation_SUITE
%%%
%%% Description:
%%% Test HTML validation
%%%
%%% The suites used for the test are located in the data directory.
%%%-------------------------------------------------------------------
-module(ct_html_validation_SUITE).

-compile(export_all).

-include("ct_results_parser.hrl").
-include_lib("common_test/include/ct.hrl").

%%--------------------------------------------------------------------
%% TEST SERVER CALLBACK FUNCTIONS
%%--------------------------------------------------------------------

%%--------------------------------------------------------------------
%% Description: Since Common Test starts another Test Server
%% instance, the tests need to be performed on a separate node (or
%% there will be clashes with logging processes etc).
%%--------------------------------------------------------------------
init_per_suite(Config0) ->
    DataDir = ?config(data_dir, Config0),
    Config = ct_test_support:init_per_suite(Config0),
    SpecsDir = filename:join(DataDir, "specs"),
    [{specs_dir, SpecsDir} | Config].

end_per_suite(Config) ->
    ct_test_support:end_per_suite(Config).

init_per_testcase(TestCase, Config) ->
    ct_test_support:init_per_testcase(TestCase, Config).

end_per_testcase(TestCase, Config) ->
    ct_test_support:end_per_testcase(TestCase, Config).

suite() -> [{ct_hooks,[ts_install_cth]}].

all() ->
    [run_spec_twice
    ].

groups() ->
    [].

init_per_group(_GroupName, Config) ->
	Config.

end_per_group(_GroupName, Config) ->
	Config.

%%--------------------------------------------------------------------
%% TEST CASES
%%--------------------------------------------------------------------

%%%-----------------------------------------------------------------
%%%

run_spec_twice(Config) ->
    Specs0 = specs(?FUNCTION_NAME),
    Specs1 = lists:append(Specs0, Specs0),
    Specs = [fname(specs_dir, Spec,Config) || Spec <- Specs1],

    setup_and_execute(?FUNCTION_NAME, Specs, [], Config).

%%%-----------------------------------------------------------------
%%% HELP FUNCTIONS
%%%-----------------------------------------------------------------

check_parameter(TCID) ->
    {ok, {config, TCID}}.

read_config(TCID) ->
    {ok, [{tcname, list_to_atom(TCID)}]}.

fname(Tag, File, Config) ->
    filename:join(?config(Tag, Config), File).

specs(run_spec_twice) ->
    [tests1_spec,
     tests2_spec].

get_default_expected(Config) ->
    #test{start_date = calendar:local_time(),
          node = ?config(ct_node, Config)}.

expected(Label, Config) ->
    Test = get_default_expected(Config),
    [Test#test{test_name = ?config(data_dir, Config) ++ ".tests1",
              label = Label,
              ok = 32,
              failed = 0,
              skipped = 0,
              user_skipped = 0,
              auto_skipped = 0,
              missing_suites = 0
             }].

modify_expected(Expected0, run_spec_twice) ->
    WithLink = lists:map(fun(E) -> E#test{old_runs_link = link} end, Expected0),
    Duplicated = lists:foldl(fun(E, Acc) -> [E, E | Acc] end, [], Expected0),
    {WithLink, Duplicated}.

setup_and_execute(TCName, Specs, TestOpts, Config) ->
    TestID = {userconfig, {?MODULE, atom_to_list(TCName)}},
    TestTerms = [TestID, {spec, Specs}, {label, TCName}] ++ TestOpts,

    Opts0 = ct_test_support:get_opts(Config),
    Opts = ct_test_support:get_overwritten_opts(Opts0 ++ TestTerms),

    ct_test_support:run_ct_run_test(Opts, Config),

    validate_html_files(Config, expected(TCName, Config)).

validate_html_files(Config, ExpectedTests) ->
    validate_index_html_file(Config, ExpectedTests).

validate_index_html_file(Config, ExpectedTests) ->
    PrivDir = ?config(priv_dir, Config),
    Path = filename:join(PrivDir, "index.html"),
    Tests = ct_results_parser:parse_index_html_file(Path),
    ok = ct_results_validator:validate_total(Tests),
    lists:foreach(fun(#total{}) -> ok;
                     (#test{suite_log_link = SuiteLogLink, ct_log_link = CtLogLink, old_runs_link = OldRunsLink} = Test) ->
                          validate_suite_log_file(Config, SuiteLogLink, []),
                          IndexLink = string:replace(CtLogLink, "ctlog.html", "index.html"),
                          validate_specific_index_html_file(Config, IndexLink, [Test]),
                          validate_old_runs_file(Config, OldRunsLink, [])
                  end, Tests).

validate_suite_log_file(Config, Link, ExpectedCases) ->
    PrivDir = ?config(priv_dir, Config),
    Path = filename:join(PrivDir, Link),
    Cases = ct_results_parser:parse_suite_log_file(Path),
    ok = ct_results_validator:validate_test_cases_total(Cases).

validate_specific_index_html_file(Config, Link, ExpectedTests) ->
    PrivDir = ?config(priv_dir, Config),
    Path = filename:join(PrivDir, Link),
    Tests = ct_results_parser:parse_index_html_file(Path),
    ok = ct_results_validator:validate_total(Tests).

validate_old_runs_file(_Config, undefined, _ExpectedOldRuns) ->
    ok;
validate_old_runs_file(Config, Link, ExpectedOldRuns) ->
    PrivDir = ?config(priv_dir, Config),
    Path = filename:join(PrivDir, Link),
    OldRuns = ct_results_parser:parse_old_runs_file(Path).

expected_test_cases(t1_SUITE) ->
    [#test_case{module = "t1_SUITE",
       tc = "init_per_suite",
       tc_link = "t1_suite.init_per_suite.html",
       top_log = "t1_suite.init_per_suite.html#top",
       end_log = "t1_suite.init_per_suite.html#end",
       result = ok},
     #test_case{module = "t1_SUITE",
       group = "group1",
       tc = "init_per_group",
       tc_link = "t1_suite.init_per_group.html",
       top_log = "t1_suite.init_per_group.html#top",
       end_log = "t1_suite.init_per_group.html#end",
       result = ok},
     #test_case{module = "t1_SUITE",
       group = "subgroup1a",
       tc = "init_per_group",
       tc_link = "t1_suite.init_per_group.2050.html",
       top_log = "t1_suite.init_per_group.2050.html#top",
       end_log = "t1_suite.init_per_group.2050.html#end",
       result = ok},
     #test_case{num = 1,
       module = "t1_SUITE",
       group = "subgroup1a",
       tc = "test1a",
       tc_link = "t1_suite.test1a.html",
       top_log = "t1_suite.test1a.html#top",
       end_log = "t1_suite.test1a.html#end",
       result = skipped,
       comment = ["&lt;&lt;\"Reason\"&gt;&gt;"]},
     #test_case{num = 2,
       module = "t1_SUITE",
       group = "subgroup1a",
       tc = "test1b",
       tc_link = "t1_suite.test1b.html",
       top_log = "t1_suite.test1b.html#top",
       end_log = "t1_suite.test1b.html#end",
       result = skipped,
       comment = ["init_per_testcase failed"]},
     #test_case{module = "t1_SUITE",
       group = "subgroup1a",
       tc = "end_per_group",
       tc_link = "t1_suite.end_per_group.html",
       top_log = "t1_suite.end_per_group.html#top",
       end_log = "t1_suite.end_per_group.html#end",
       result = ok},
     #test_case{module = "t1_SUITE",
       group = "subgroup1b",
       tc = "init_per_group",
       tc_link = "t1_suite.init_per_group.2114.html",
       top_log = "t1_suite.init_per_group.2114.html#top",
       end_log = "t1_suite.init_per_group.2114.html#end",
       result = ok},
     #test_case{num = 3,
       module = "t1_SUITE",
       group = "subgroup1b",
       tc = "test1c",
       tc_link = "t1_suite.test1c.html",
       top_log = "t1_suite.test1c.html#top",
       end_log = "t1_suite.test1c.html#end",
       result = ok},
     #test_case{num = 4,
       module = "t1_SUITE",
       group = "subgroup1b",
       tc = "test1d",
       tc_link = "t1_suite.test1d.html",
       top_log = "t1_suite.test1d.html#top",
       end_log = "t1_suite.test1d.html#end",
       result = ok},
     #test_case{module = "t1_SUITE",
       group = "subgroup1b",
       tc = "end_per_group",
       tc_link = "t1_suite.end_per_group.2178.html",
       top_log = "t1_suite.end_per_group.2178.html#top",
       end_log = "t1_suite.end_per_group.2178.html#end",
       result = ok},
     #test_case{module = "t1_SUITE",
       group = "group1",
       tc = "end_per_group",
       tc_link = "t1_suite.end_per_group.2242.html",
       top_log = "t1_suite.end_per_group.2242.html#top",
       end_log = "t1_suite.end_per_group.2242.html#end",
       result = ok},
     #test_case{module = "t1_SUITE",
       group = "group2",
       tc = "init_per_group",
       tc_link = "t1_suite.init_per_group.2306.html",
       top_log = "t1_suite.init_per_group.2306.html#top",
       end_log = "t1_suite.init_per_group.2306.html#end",
       result = ok},
     #test_case{module = "t1_SUITE",
       group = "subgroup2a",
       tc = "init_per_group",
       tc_link = "t1_suite.init_per_group.2370.html",
       top_log = "t1_suite.init_per_group.2370.html#top",
       end_log = "t1_suite.init_per_group.2370.html#end",
       result = ok},
     #test_case{num = 5,
       module = "t1_SUITE",
       group = "subgroup2a",
       tc = "test2a",
       tc_link = "t1_suite.test2a.html",
       top_log = "t1_suite.test2a.html#top",
       end_log = "t1_suite.test2a.html#end",
       result = ok},
     #test_case{num = 6,
       module = "t1_SUITE",
       group = "subgroup2a",
       tc = "test2b",
       tc_link = "t1_suite.test2b.html",
       top_log = "t1_suite.test2b.html#top",
       end_log = "t1_suite.test2b.html#end",
       result = ok},
     #test_case{module = "t1_SUITE",
       group = "subgroup2a",
       tc = "end_per_group",
       tc_link = "t1_suite.end_per_group.2434.html",
       top_log = "t1_suite.end_per_group.2434.html#top",
       end_log = "t1_suite.end_per_group.2434.html#end",
       result = ok},
     #test_case{module = "t1_SUITE",
       group = "subgroup2b",
       tc = "init_per_group",
       tc_link = "t1_suite.init_per_group.2498.html",
       top_log = "t1_suite.init_per_group.2498.html#top",
       end_log = "t1_suite.init_per_group.2498.html#end",
       result = ok},
     #test_case{num = 7,
       module = "t1_SUITE",
       group = "subgroup2b",
       tc = "test2c",
       tc_link = "t1_suite.test2c.html",
       top_log = "t1_suite.test2c.html#top",
       end_log = "t1_suite.test2c.html#end",
       result = ok},
     #test_case{num = 8,
       module = "t1_SUITE",
       group = "subgroup2b",
       tc = "test2d",
       tc_link = "t1_suite.test2d.html",
       top_log = "t1_suite.test2d.html#top",
       end_log = "t1_suite.test2d.html#end",
       result = ok},
     #test_case{module = "t1_SUITE",
       group = "subgroup2b",
       tc = "end_per_group",
       tc_link = "t1_suite.end_per_group.2562.html",
       top_log = "t1_suite.end_per_group.2562.html#top",
       end_log = "t1_suite.end_per_group.2562.html#end",
       result = ok},
     #test_case{module = "t1_SUITE",
       group = "group2",
       tc = "end_per_group",
       tc_link = "t1_suite.end_per_group.2626.html",
       top_log = "t1_suite.end_per_group.2626.html#top",
       end_log = "t1_suite.end_per_group.2626.html#end",
       result = ok},
     #test_case{module = "t1_SUITE",
       tc = "end_per_suite",
       tc_link = "t1_suite.end_per_suite.html",
       top_log = "t1_suite.end_per_suite.html#top",
       end_log = "t1_suite.end_per_suite.html#end",
       result = ok}];
expected_test_cases(t2_SUITE) ->
    [#test_case{module = "t2_SUITE",
       tc = "init_per_suite",
       tc_link = "t2_suite.init_per_suite.html",
       top_log = "t2_suite.init_per_suite.html#top",
       end_log = "t2_suite.init_per_suite.html#end",
       result = ok},
     #test_case{module = "t2_SUITE",
       group = "group1",
       tc = "init_per_group",
       tc_link = "t2_suite.init_per_group.html",
       top_log = "t2_suite.init_per_group.html#top",
       end_log = "t2_suite.init_per_group.html#end",
       result = ok},
     #test_case{module = "t2_SUITE",
       group = "subgroup1a",
       tc = "init_per_group",
       tc_link = "t2_suite.init_per_group.2690.html",
       top_log = "t2_suite.init_per_group.2690.html#top",
       end_log = "t2_suite.init_per_group.2690.html#end",
       result = ok},
     #test_case{num = 9,
       module = "t2_SUITE",
       group = "subgroup1a",
       tc = "test1a",
       tc_link = "t2_suite.test1a.html",
       top_log = "t2_suite.test1a.html#top",
       end_log = "t2_suite.test1a.html#end",
       result = failed,
       comment = ["{test_server,ts_tc,1796}",
       "{test_case_failed,deliberate failure}"]},
     #test_case{num = 10,
       module = "t2_SUITE",
       group = "subgroup1a",
       tc = "test1b",
       tc_link = "t2_suite.test1b.html",
       top_log = "t2_suite.test1b.html#top",
       end_log = "t2_suite.test1b.html#end",
       result = failed,
       comment = ["{t2_SUITE,test1b,<a href=\"t2_suite.src.html#37\">37</a>}",
       "{crash_on_purpose,[{t2_SUITE,...},{...}|...]}"]},
     #test_case{module = "t2_SUITE",
       group = "subgroup1a",
       tc = "end_per_group",
       tc_link = "t2_suite.end_per_group.html",
       top_log = "t2_suite.end_per_group.html#top",
       end_log = "t2_suite.end_per_group.html#end",
       result = ok},
     #test_case{module = "t2_SUITE",
       group = "subgroup1b",
       tc = "init_per_group",
       tc_link = "t2_suite.init_per_group.2754.html",
       top_log = "t2_suite.init_per_group.2754.html#top",
       end_log = "t2_suite.init_per_group.2754.html#end",
       result = ok},
     #test_case{num = 11,
       module = "t2_SUITE",
       group = "subgroup1b",
       tc = "test1c",
       tc_link = "t2_suite.test1c.html",
       top_log = "t2_suite.test1c.html#top",
       end_log = "t2_suite.test1c.html#end",
       result = ok},
     #test_case{num = 12,
       module = "t2_SUITE",
       group = "subgroup1b",
       tc = "test1d",
       tc_link = "t2_suite.test1d.html",
       top_log = "t2_suite.test1d.html#top",
       end_log = "t2_suite.test1d.html#end",
       result = ok},
     #test_case{module = "t2_SUITE",
       group = "subgroup1b",
       tc = "end_per_group",
       tc_link = "t2_suite.end_per_group.2818.html",
       top_log = "t2_suite.end_per_group.2818.html#top",
       end_log = "t2_suite.end_per_group.2818.html#end",
       result = ok},
     #test_case{module = "t2_SUITE",
       group = "group1",
       tc = "end_per_group",
       tc_link = "t2_suite.end_per_group.2882.html",
       top_log = "t2_suite.end_per_group.2882.html#top",
       end_log = "t2_suite.end_per_group.2882.html#end",
       result = ok},
     #test_case{module = "t2_SUITE",
       group = "group2",
       tc = "init_per_group",
       tc_link = "t2_suite.init_per_group.2946.html",
       top_log = "t2_suite.init_per_group.2946.html#top",
       end_log = "t2_suite.init_per_group.2946.html#end",
       result = ok},
     #test_case{module = "t2_SUITE",
       group = "subgroup2a",
       tc = "init_per_group",
       tc_link = "t2_suite.init_per_group.3010.html",
       top_log = "t2_suite.init_per_group.3010.html#top",
       end_log = "t2_suite.init_per_group.3010.html#end",
       result = ok},
     #test_case{num = 13,
       module = "t2_SUITE",
       group = "subgroup2a",
       tc = "test2a",
       tc_link = "t2_suite.test2a.html",
       top_log = "t2_suite.test2a.html#top",
       end_log = "t2_suite.test2a.html#end",
       result = ok},
     #test_case{num = 14,
       module = "t2_SUITE",
       group = "subgroup2a",
       tc = "test2b",
       tc_link = "t2_suite.test2b.html",
       top_log = "t2_suite.test2b.html#top",
       end_log = "t2_suite.test2b.html#end",
       result = ok},
     #test_case{module = "t2_SUITE",
       group = "subgroup2a",
       tc = "end_per_group",
       tc_link = "t2_suite.end_per_group.3074.html",
       top_log = "t2_suite.end_per_group.3074.html#top",
       end_log = "t2_suite.end_per_group.3074.html#end",
       result = ok},
     #test_case{module = "t2_SUITE",
       group = "subgroup2b",
       tc = "init_per_group",
       tc_link = "t2_suite.init_per_group.3138.html",
       top_log = "t2_suite.init_per_group.3138.html#top",
       end_log = "t2_suite.init_per_group.3138.html#end",
       result = ok},
     #test_case{num = 15,
       module = "t2_SUITE",
       group = "subgroup2b",
       tc = "test2c",
       tc_link = "t2_suite.test2c.html",
       top_log = "t2_suite.test2c.html#top",
       end_log = "t2_suite.test2c.html#end",
       result = ok},
     #test_case{num = 16,
       module = "t2_SUITE",
       group = "subgroup2b",
       tc = "test2d",
       tc_link = "t2_suite.test2d.html",
       top_log = "t2_suite.test2d.html#top",
       end_log = "t2_suite.test2d.html#end",
       result = ok},
     #test_case{module = "t2_SUITE",
       group = "subgroup2b",
       tc = "end_per_group",
       tc_link = "t2_suite.end_per_group.3202.html",
       top_log = "t2_suite.end_per_group.3202.html#top",
       end_log = "t2_suite.end_per_group.3202.html#end",
       result = ok},
     #test_case{module = "t2_SUITE",
       group = "group2",
       tc = "end_per_group",
       tc_link = "t2_suite.end_per_group.3266.html",
       top_log = "t2_suite.end_per_group.3266.html#top",
       end_log = "t2_suite.end_per_group.3266.html#end",
       result = ok},
     #test_case{module = "t2_SUITE",
       tc = "end_per_suite",
       tc_link = "t2_suite.end_per_suite.html",
       top_log = "t2_suite.end_per_suite.html#top",
       end_log = "t2_suite.end_per_suite.html#end",
       result = ok}];
expected_test_cases(t3_SUITE) ->
    [#test_case{module = "t3_SUITE",
       tc = "init_per_suite",
       tc_link = "t3_suite.init_per_suite.html",
       top_log = "t3_suite.init_per_suite.html#top",
       end_log = "t3_suite.init_per_suite.html#end",
       result = ok},
     #test_case{module = "t3_SUITE",
       group = "group1",
       tc = "init_per_group",
       tc_link = "t3_suite.init_per_group.html",
       top_log = "t3_suite.init_per_group.html#top",
       end_log = "t3_suite.init_per_group.html#end",
       result = ok},
     #test_case{module = "t3_SUITE",
       group = "subgroup1a",
       tc = "init_per_group",
       tc_link = "t3_suite.init_per_group.3330.html",
       top_log = "t3_suite.init_per_group.3330.html#top",
       end_log = "t3_suite.init_per_group.3330.html#end",
       result = failed,
       comment = ["{test_server,ts_tc,1796}",
       "{test_case_failed,init_per_group subgroup1a failure}"]},
     #test_case{num = 17,
       module = "t3_SUITE",
       group = "subgroup1a",
       tc = "test1a",
       result = skipped,
       comment = ["init_per_group failed"]},
     #test_case{num = 18,
       module = "t3_SUITE",
       group = "subgroup1a",
       tc = "test1b",
       result = skipped,
       comment = ["init_per_group failed"]},
     #test_case{module = "t3_SUITE",
       group = "subgroup1a",
       tc = "end_per_group",
       result = skipped,
       comment = ["init_per_group failed"]},
     #test_case{module = "t3_SUITE",
       group = "subgroup1b",
       tc = "init_per_group",
       tc_link = "t3_suite.init_per_group.3394.html",
       top_log = "t3_suite.init_per_group.3394.html#top",
       end_log = "t3_suite.init_per_group.3394.html#end",
       result = ok},
     #test_case{num = 19,
       module = "t3_SUITE",
       group = "subgroup1b",
       tc = "test1c",
       tc_link = "t3_suite.test1c.html",
       top_log = "t3_suite.test1c.html#top",
       end_log = "t3_suite.test1c.html#end",
       result = ok},
     #test_case{num = 20,
       module = "t3_SUITE",
       group = "subgroup1b",
       tc = "test1d",
       tc_link = "t3_suite.test1d.html",
       top_log = "t3_suite.test1d.html#top",
       end_log = "t3_suite.test1d.html#end",
       result = ok},
     #test_case{module = "t3_SUITE",
       group = "subgroup1b",
       tc = "end_per_group",
       tc_link = "t3_suite.end_per_group.html",
       top_log = "t3_suite.end_per_group.html#top",
       end_log = "t3_suite.end_per_group.html#end",
       result = ok},
     #test_case{module = "t3_SUITE",
       group = "group1",
       tc = "end_per_group",
       tc_link = "t3_suite.end_per_group.3458.html",
       top_log = "t3_suite.end_per_group.3458.html#top",
       end_log = "t3_suite.end_per_group.3458.html#end",
       result = ok},
     #test_case{module = "t3_SUITE",
       group = "group2",
       tc = "init_per_group",
       tc_link = "t3_suite.init_per_group.3522.html",
       top_log = "t3_suite.init_per_group.3522.html#top",
       end_log = "t3_suite.init_per_group.3522.html#end",
       result = ok},
     #test_case{module = "t3_SUITE",
       group = "subgroup2a",
       tc = "init_per_group",
       tc_link = "t3_suite.init_per_group.3586.html",
       top_log = "t3_suite.init_per_group.3586.html#top",
       end_log = "t3_suite.init_per_group.3586.html#end",
       result = ok},
     #test_case{num = 21,
       module = "t3_SUITE",
       group = "subgroup2a",
       tc = "test2a",
       tc_link = "t3_suite.test2a.html",
       top_log = "t3_suite.test2a.html#top",
       end_log = "t3_suite.test2a.html#end",
       result = ok},
     #test_case{num = 22,
       module = "t3_SUITE",
       group = "subgroup2a",
       tc = "test2b",
       tc_link = "t3_suite.test2b.html",
       top_log = "t3_suite.test2b.html#top",
       end_log = "t3_suite.test2b.html#end",
       result = ok},
     #test_case{module = "t3_SUITE",
       group = "subgroup2a",
       tc = "end_per_group",
       tc_link = "t3_suite.end_per_group.3650.html",
       top_log = "t3_suite.end_per_group.3650.html#top",
       end_log = "t3_suite.end_per_group.3650.html#end",
       result = ok},
     #test_case{module = "t3_SUITE",
       group = "subgroup2b",
       tc = "init_per_group",
       tc_link = "t3_suite.init_per_group.3714.html",
       top_log = "t3_suite.init_per_group.3714.html#top",
       end_log = "t3_suite.init_per_group.3714.html#end",
       result = ok},
     #test_case{num = 23,
       module = "t3_SUITE",
       group = "subgroup2b",
       tc = "test2c",
       tc_link = "t3_suite.test2c.html",
       top_log = "t3_suite.test2c.html#top",
       end_log = "t3_suite.test2c.html#end",
       result = ok},
     #test_case{num = 24,
       module = "t3_SUITE",
       group = "subgroup2b",
       tc = "test2d",
       tc_link = "t3_suite.test2d.html",
       top_log = "t3_suite.test2d.html#top",
       end_log = "t3_suite.test2d.html#end",
       result = ok},
     #test_case{module = "t3_SUITE",
       group = "subgroup2b",
       tc = "end_per_group",
       tc_link = "t3_suite.end_per_group.3778.html",
       top_log = "t3_suite.end_per_group.3778.html#top",
       end_log = "t3_suite.end_per_group.3778.html#end",
       result = ok},
     #test_case{module = "t3_SUITE",
       group = "group2",
       tc = "end_per_group",
       tc_link = "t3_suite.end_per_group.3842.html",
       top_log = "t3_suite.end_per_group.3842.html#top",
       end_log = "t3_suite.end_per_group.3842.html#end",
       result = ok},
     #test_case{module = "t3_SUITE",
       tc = "end_per_suite",
       tc_link = "t3_suite.end_per_suite.html",
       top_log = "t3_suite.end_per_suite.html#top",
       end_log = "t3_suite.end_per_suite.html#end",
       result = ok}];
expected_test_cases(t4_SUITE) ->
    [#test_case{module = "t4_SUITE",
       tc = "init_per_suite",
       tc_link = "t4_suite.init_per_suite.html",
       top_log = "t4_suite.init_per_suite.html#top",
       end_log = "t4_suite.init_per_suite.html#end",
       result = ok},
     #test_case{module = "t4_SUITE",
       group = "group1",
       tc = "init_per_group",
       tc_link = "t4_suite.init_per_group.html",
       top_log = "t4_suite.init_per_group.html#top",
       end_log = "t4_suite.init_per_group.html#end",
       result = ok},
     #test_case{module = "t4_SUITE",
       group = "subgroup1a",
       tc = "init_per_group",
       tc_link = "t4_suite.init_per_group.3906.html",
       top_log = "t4_suite.init_per_group.3906.html#top",
       end_log = "t4_suite.init_per_group.3906.html#end",
       result = ok},
     #test_case{num = 25,
       module = "t4_SUITE",
       group = "subgroup1a",
       tc = "test1a",
       tc_link = "t4_suite.test1a.html",
       top_log = "t4_suite.test1a.html#top",
       end_log = "t4_suite.test1a.html#end",
       result = ok},
     #test_case{num = 26,
       module = "t4_SUITE",
       group = "subgroup1a",
       tc = "test1b",
       tc_link = "t4_suite.test1b.html",
       top_log = "t4_suite.test1b.html#top",
       end_log = "t4_suite.test1b.html#end",
       result = ok},
     #test_case{module = "t4_SUITE",
       group = "subgroup1a",
       tc = "end_per_group",
       tc_link = "t4_suite.end_per_group.html",
       top_log = "t4_suite.end_per_group.html#top",
       end_log = "t4_suite.end_per_group.html#end",
       result = ok},
     #test_case{module = "t4_SUITE",
       group = "subgroup1b",
       tc = "init_per_group",
       tc_link = "t4_suite.init_per_group.3970.html",
       top_log = "t4_suite.init_per_group.3970.html#top",
       end_log = "t4_suite.init_per_group.3970.html#end",
       result = ok},
     #test_case{num = 27,
       module = "t4_SUITE",
       group = "subgroup1b",
       tc = "test1c",
       tc_link = "t4_suite.test1c.html",
       top_log = "t4_suite.test1c.html#top",
       end_log = "t4_suite.test1c.html#end",
       result = ok},
     #test_case{num = 28,
       module = "t4_SUITE",
       group = "subgroup1b",
       tc = "test1d",
       tc_link = "t4_suite.test1d.html",
       top_log = "t4_suite.test1d.html#top",
       end_log = "t4_suite.test1d.html#end",
       result = ok},
     #test_case{module = "t4_SUITE",
       group = "subgroup1b",
       tc = "end_per_group",
       tc_link = "t4_suite.end_per_group.4034.html",
       top_log = "t4_suite.end_per_group.4034.html#top",
       end_log = "t4_suite.end_per_group.4034.html#end",
       result = ok},
     #test_case{module = "t4_SUITE",
       group = "group1",
       tc = "end_per_group",
       tc_link = "t4_suite.end_per_group.4098.html",
       top_log = "t4_suite.end_per_group.4098.html#top",
       end_log = "t4_suite.end_per_group.4098.html#end",
       result = ok},
     #test_case{module = "t4_SUITE",
       group = "group2",
       tc = "init_per_group",
       tc_link = "t4_suite.init_per_group.4162.html",
       top_log = "t4_suite.init_per_group.4162.html#top",
       end_log = "t4_suite.init_per_group.4162.html#end",
       result = ok},
     #test_case{module = "t4_SUITE",
       group = "subgroup2a",
       tc = "init_per_group",
       tc_link = "t4_suite.init_per_group.4226.html",
       top_log = "t4_suite.init_per_group.4226.html#top",
       end_log = "t4_suite.init_per_group.4226.html#end",
       result = ok},
     #test_case{num = 29,
       module = "t4_SUITE",
       group = "subgroup2a",
       tc = "test2a",
       tc_link = "t4_suite.test2a.html",
       top_log = "t4_suite.test2a.html#top",
       end_log = "t4_suite.test2a.html#end",
       result = ok},
     #test_case{num = 30,
       module = "t4_SUITE",
       group = "subgroup2a",
       tc = "test2b",
       tc_link = "t4_suite.test2b.html",
       top_log = "t4_suite.test2b.html#top",
       end_log = "t4_suite.test2b.html#end",
       result = ok},
     #test_case{module = "t4_SUITE",
       group = "subgroup2a",
       tc = "end_per_group",
       tc_link = "t4_suite.end_per_group.4290.html",
       top_log = "t4_suite.end_per_group.4290.html#top",
       end_log = "t4_suite.end_per_group.4290.html#end",
       result = failed,
       comment = ["{test_server,ts_tc,1796}",
       "{test_case_failed,end_per_group subgroup2a failure}"]},
     #test_case{module = "t4_SUITE",
       group = "subgroup2b",
       tc = "init_per_group",
       tc_link = "t4_suite.init_per_group.4354.html",
       top_log = "t4_suite.init_per_group.4354.html#top",
       end_log = "t4_suite.init_per_group.4354.html#end",
       result = ok},
     #test_case{num = 31,
       module = "t4_SUITE",
       group = "subgroup2b",
       tc = "test2c",
       tc_link = "t4_suite.test2c.html",
       top_log = "t4_suite.test2c.html#top",
       end_log = "t4_suite.test2c.html#end",
       result = ok},
     #test_case{num = 32,
       module = "t4_SUITE",
       group = "subgroup2b",
       tc = "test2d",
       tc_link = "t4_suite.test2d.html",
       top_log = "t4_suite.test2d.html#top",
       end_log = "t4_suite.test2d.html#end",
       result = ok},
     #test_case{module = "t4_SUITE",
       group = "subgroup2b",
       tc = "end_per_group",
       tc_link = "t4_suite.end_per_group.4418.html",
       top_log = "t4_suite.end_per_group.4418.html#top",
       end_log = "t4_suite.end_per_group.4418.html#end",
       result = ok},
     #test_case{module = "t4_SUITE",
       group = "group2",
       tc = "end_per_group",
       tc_link = "t4_suite.end_per_group.4482.html",
       top_log = "t4_suite.end_per_group.4482.html#top",
       end_log = "t4_suite.end_per_group.4482.html#end",
       result = ok},
     #test_case{module = "t4_SUITE",
       tc = "end_per_suite",
       tc_link = "t4_suite.end_per_suite.html",
       top_log = "t4_suite.end_per_suite.html#top",
       end_log = "t4_suite.end_per_suite.html#end",
       result = ok}];
expected_test_cases(t5_SUITE) ->
    [#test_case{module = "t5_SUITE",
       tc = "init_per_suite",
       tc_link = "t5_suite.init_per_suite.html",
       top_log = "t5_suite.init_per_suite.html#top",
       end_log = "t5_suite.init_per_suite.html#end",
       result = failed,
       comment = ["{test_server,ts_tc,1796}",
       "{test_case_failed,init_per_suite failure}"]},
     #test_case{num = 1,
       module = "t5_SUITE",
       group = "subgroup1a",
       tc = "test1a",
       result = skipped,
       comment = ["init_per_suite failed"]},
     #test_case{num = 2,
       module = "t5_SUITE",
       group = "subgroup1a",
       tc = "test1b",
       result = skipped,
       comment = ["init_per_suite failed"]},
     #test_case{num = 3,
       module = "t5_SUITE",
       group = "subgroup1b",
       tc = "test1c",
       result = skipped,
       comment = ["init_per_suite failed"]},
     #test_case{num = 4,
       module = "t5_SUITE",
       group = "subgroup1b",
       tc = "test1d",
       result = skipped,
       comment = ["init_per_suite failed"]},
     #test_case{num = 5,
       module = "t5_SUITE",
       group = "subgroup2a",
       tc = "test2a",
       result = skipped,
       comment = ["init_per_suite failed"]},
     #test_case{num = 6,
       module = "t5_SUITE",
       group = "subgroup2a",
       tc = "test2b",
       result = skipped,
       comment = ["init_per_suite failed"]},
     #test_case{num = 7,
       module = "t5_SUITE",
       group = "subgroup2b",
       tc = "test2c",
       result = skipped,
       comment = ["init_per_suite failed"]},
     #test_case{num = 8,
       module = "t5_SUITE",
       group = "subgroup2b",
       tc = "test2d",
       result = skipped,
       comment = ["init_per_suite failed"]},
     #test_case{module = "t5_SUITE",
       tc = "end_per_suite",
       result = skipped,
       comment = ["init_per_suite failed"]}];
expected_test_cases(t6_SUITE) ->
    [#test_case{module = "t6_SUITE",
       tc = "init_per_suite",
       tc_link = "t6_suite.init_per_suite.html",
       top_log = "t6_suite.init_per_suite.html#top",
       end_log = "t6_suite.init_per_suite.html#end",
       result = ok},
     #test_case{module = "t6_SUITE",
       group = "group1",
       tc = "init_per_group",
       tc_link = "t6_suite.init_per_group.html",
       top_log = "t6_suite.init_per_group.html#top",
       end_log = "t6_suite.init_per_group.html#end",
       result = ok},
     #test_case{module = "t6_SUITE",
       group = "subgroup1a",
       tc = "init_per_group",
       tc_link = "t6_suite.init_per_group.4546.html",
       top_log = "t6_suite.init_per_group.4546.html#top",
       end_log = "t6_suite.init_per_group.4546.html#end",
       result = ok},
     #test_case{num = 9,
       module = "t6_SUITE",
       group = "subgroup1a",
       tc = "test1a",
       tc_link = "t6_suite.test1a.html",
       top_log = "t6_suite.test1a.html#top",
       end_log = "t6_suite.test1a.html#end",
       result = ok},
     #test_case{num = 10,
       module = "t6_SUITE",
       group = "subgroup1a",
       tc = "test1b",
       tc_link = "t6_suite.test1b.html",
       top_log = "t6_suite.test1b.html#top",
       end_log = "t6_suite.test1b.html#end",
       result = ok},
     #test_case{module = "t6_SUITE",
       group = "subgroup1a",
       tc = "end_per_group",
       tc_link = "t6_suite.end_per_group.html",
       top_log = "t6_suite.end_per_group.html#top",
       end_log = "t6_suite.end_per_group.html#end",
       result = ok},
     #test_case{module = "t6_SUITE",
       group = "subgroup1b",
       tc = "init_per_group",
       tc_link = "t6_suite.init_per_group.4610.html",
       top_log = "t6_suite.init_per_group.4610.html#top",
       end_log = "t6_suite.init_per_group.4610.html#end",
       result = ok},
     #test_case{num = 11,
       module = "t6_SUITE",
       group = "subgroup1b",
       tc = "test1c",
       tc_link = "t6_suite.test1c.html",
       top_log = "t6_suite.test1c.html#top",
       end_log = "t6_suite.test1c.html#end",
       result = ok},
     #test_case{num = 12,
       module = "t6_SUITE",
       group = "subgroup1b",
       tc = "test1d",
       tc_link = "t6_suite.test1d.html",
       top_log = "t6_suite.test1d.html#top",
       end_log = "t6_suite.test1d.html#end",
       result = ok},
     #test_case{module = "t6_SUITE",
       group = "subgroup1b",
       tc = "end_per_group",
       tc_link = "t6_suite.end_per_group.4674.html",
       top_log = "t6_suite.end_per_group.4674.html#top",
       end_log = "t6_suite.end_per_group.4674.html#end",
       result = ok},
     #test_case{module = "t6_SUITE",
       group = "group1",
       tc = "end_per_group",
       tc_link = "t6_suite.end_per_group.4738.html",
       top_log = "t6_suite.end_per_group.4738.html#top",
       end_log = "t6_suite.end_per_group.4738.html#end",
       result = ok},
     #test_case{module = "t6_SUITE",
       group = "group2",
       tc = "init_per_group",
       tc_link = "t6_suite.init_per_group.4802.html",
       top_log = "t6_suite.init_per_group.4802.html#top",
       end_log = "t6_suite.init_per_group.4802.html#end",
       result = ok},
     #test_case{module = "t6_SUITE",
       group = "subgroup2a",
       tc = "init_per_group",
       tc_link = "t6_suite.init_per_group.4866.html",
       top_log = "t6_suite.init_per_group.4866.html#top",
       end_log = "t6_suite.init_per_group.4866.html#end",
       result = ok},
     #test_case{num = 13,
       module = "t6_SUITE",
       group = "subgroup2a",
       tc = "test2a",
       tc_link = "t6_suite.test2a.html",
       top_log = "t6_suite.test2a.html#top",
       end_log = "t6_suite.test2a.html#end",
       result = ok},
     #test_case{num = 14,
       module = "t6_SUITE",
       group = "subgroup2a",
       tc = "test2b",
       tc_link = "t6_suite.test2b.html",
       top_log = "t6_suite.test2b.html#top",
       end_log = "t6_suite.test2b.html#end",
       result = ok},
     #test_case{module = "t6_SUITE",
       group = "subgroup2a",
       tc = "end_per_group",
       tc_link = "t6_suite.end_per_group.4930.html",
       top_log = "t6_suite.end_per_group.4930.html#top",
       end_log = "t6_suite.end_per_group.4930.html#end",
       result = ok},
     #test_case{module = "t6_SUITE",
       group = "subgroup2b",
       tc = "init_per_group",
       tc_link = "t6_suite.init_per_group.4994.html",
       top_log = "t6_suite.init_per_group.4994.html#top",
       end_log = "t6_suite.init_per_group.4994.html#end",
       result = ok},
     #test_case{num = 15,
       module = "t6_SUITE",
       group = "subgroup2b",
       tc = "test2c",
       tc_link = "t6_suite.test2c.html",
       top_log = "t6_suite.test2c.html#top",
       end_log = "t6_suite.test2c.html#end",
       result = ok},
     #test_case{num = 16,
       module = "t6_SUITE",
       group = "subgroup2b",
       tc = "test2d",
       tc_link = "t6_suite.test2d.html",
       top_log = "t6_suite.test2d.html#top",
       end_log = "t6_suite.test2d.html#end",
       result = ok},
     #test_case{module = "t6_SUITE",
       group = "subgroup2b",
       tc = "end_per_group",
       tc_link = "t6_suite.end_per_group.5058.html",
       top_log = "t6_suite.end_per_group.5058.html#top",
       end_log = "t6_suite.end_per_group.5058.html#end",
       result = ok},
     #test_case{module = "t6_SUITE",
       group = "group2",
       tc = "end_per_group",
       tc_link = "t6_suite.end_per_group.5122.html",
       top_log = "t6_suite.end_per_group.5122.html#top",
       end_log = "t6_suite.end_per_group.5122.html#end",
       result = ok},
     #test_case{module = "t6_SUITE",
       tc = "end_per_suite",
       tc_link = "t6_suite.end_per_suite.html",
       top_log = "t6_suite.end_per_suite.html#top",
       end_log = "t6_suite.end_per_suite.html#end",
       result = failed,
       comment = ["{test_server,ts_tc,1796}",
       "{test_case_failed,end_per_suite failure}"]}
    ];
expected_test_cases(t7_SUITE) ->
    [#test_case{module = "t7_SUITE",
       tc = "init_per_suite",
       tc_link = "t7_suite.init_per_suite.html",
       top_log = "t7_suite.init_per_suite.html#top",
       end_log = "t7_suite.init_per_suite.html#end",
       result = ok},
     #test_case{module = "t7_SUITE",
       group = "group1",
       tc = "init_per_group",
       tc_link = "t7_suite.init_per_group.html",
       top_log = "t7_suite.init_per_group.html#top",
       end_log = "t7_suite.init_per_group.html#end",
       result = ok},
     #test_case{module = "t7_SUITE",
       group = "subgroup1a",
       tc = "init_per_group",
       tc_link = "t7_suite.init_per_group.5186.html",
       top_log = "t7_suite.init_per_group.5186.html#top",
       end_log = "t7_suite.init_per_group.5186.html#end",
       result = ok},
     #test_case{num = 17,
       module = "t7_SUITE",
       group = "subgroup1a",
       tc = "test1a",
       tc_link = "t7_suite.test1a.html",
       top_log = "t7_suite.test1a.html#top",
       end_log = "t7_suite.test1a.html#end",
       result = ok,
       comment = ["WARNING: end_per_testcase crashed!\n"]},
     #test_case{num = 18,
       module = "t7_SUITE",
       group = "subgroup1a",
       tc = "test1b",
       tc_link = "t7_suite.test1b.html",
       top_log = "t7_suite.test1b.html#top",
       end_log = "t7_suite.test1b.html#end",
       result = ok},
     #test_case{module = "t7_SUITE",
       group = "subgroup1a",
       tc = "end_per_group",
       tc_link = "t7_suite.end_per_group.html",
       top_log = "t7_suite.end_per_group.html#top",
       end_log = "t7_suite.end_per_group.html#end",
       result = ok},
     #test_case{module = "t7_SUITE",
       group = "subgroup1b",
       tc = "init_per_group",
       tc_link = "t7_suite.init_per_group.5250.html",
       top_log = "t7_suite.init_per_group.5250.html#top",
       end_log = "t7_suite.init_per_group.5250.html#end",
       result = ok},
     #test_case{num = 19,
       module = "t7_SUITE",
       group = "subgroup1b",
       tc = "test1c",
       tc_link = "t7_suite.test1c.html",
       top_log = "t7_suite.test1c.html#top",
       end_log = "t7_suite.test1c.html#end",
       result = ok},
     #test_case{num = 20,
       module = "t7_SUITE",
       group = "subgroup1b",
       tc = "test1d",
       tc_link = "t7_suite.test1d.html",
       top_log = "t7_suite.test1d.html#top",
       end_log = "t7_suite.test1d.html#end",
       result = ok},
     #test_case{module = "t7_SUITE",
       group = "subgroup1b",
       tc = "end_per_group",
       tc_link = "t7_suite.end_per_group.5314.html",
       top_log = "t7_suite.end_per_group.5314.html#top",
       end_log = "t7_suite.end_per_group.5314.html#end",
       result = ok},
     #test_case{module = "t7_SUITE",
       group = "group1",
       tc = "end_per_group",
       tc_link = "t7_suite.end_per_group.5378.html",
       top_log = "t7_suite.end_per_group.5378.html#top",
       end_log = "t7_suite.end_per_group.5378.html#end",
       result = ok},
     #test_case{module = "t7_SUITE",
       group = "group2",
       tc = "init_per_group",
       tc_link = "t7_suite.init_per_group.5442.html",
       top_log = "t7_suite.init_per_group.5442.html#top",
       end_log = "t7_suite.init_per_group.5442.html#end",
       result = ok},
     #test_case{module = "t7_SUITE",
       group = "subgroup2a",
       tc = "init_per_group",
       tc_link = "t7_suite.init_per_group.5506.html",
       top_log = "t7_suite.init_per_group.5506.html#top",
       end_log = "t7_suite.init_per_group.5506.html#end",
       result = ok},
     #test_case{num = 21,
       module = "t7_SUITE",
       group = "subgroup2a",
       tc = "test2a",
       tc_link = "t7_suite.test2a.html",
       top_log = "t7_suite.test2a.html#top",
       end_log = "t7_suite.test2a.html#end",
       result = ok},
     #test_case{num = 22,
       module = "t7_SUITE",
       group = "subgroup2a",
       tc = "test2b",
       tc_link = "t7_suite.test2b.html",
       top_log = "t7_suite.test2b.html#top",
       end_log = "t7_suite.test2b.html#end",
       result = ok},
     #test_case{module = "t7_SUITE",
       group = "subgroup2a",
       tc = "end_per_group",
       tc_link = "t7_suite.end_per_group.5570.html",
       top_log = "t7_suite.end_per_group.5570.html#top",
       end_log = "t7_suite.end_per_group.5570.html#end",
       result = ok},
     #test_case{module = "t7_SUITE",
       group = "subgroup2b",
       tc = "init_per_group",
       tc_link = "t7_suite.init_per_group.5634.html",
       top_log = "t7_suite.init_per_group.5634.html#top",
       end_log = "t7_suite.init_per_group.5634.html#end",
       result = ok},
     #test_case{num = 23,
       module = "t7_SUITE",
       group = "subgroup2b",
       tc = "test2c",
       tc_link = "t7_suite.test2c.html",
       top_log = "t7_suite.test2c.html#top",
       end_log = "t7_suite.test2c.html#end",
       result = ok},
     #test_case{num = 24,
       module = "t7_SUITE",
       group = "subgroup2b",
       tc = "test2d",
       tc_link = "t7_suite.test2d.html",
       top_log = "t7_suite.test2d.html#top",
       end_log = "t7_suite.test2d.html#end",
       result = ok},
     #test_case{module = "t7_SUITE",
       group = "subgroup2b",
       tc = "end_per_group",
       tc_link = "t7_suite.end_per_group.5698.html",
       top_log = "t7_suite.end_per_group.5698.html#top",
       end_log = "t7_suite.end_per_group.5698.html#end",
       result = ok},
     #test_case{module = "t7_SUITE",
       group = "group2",
       tc = "end_per_group",
       tc_link = "t7_suite.end_per_group.5762.html",
       top_log = "t7_suite.end_per_group.5762.html#top",
       end_log = "t7_suite.end_per_group.5762.html#end",
       result = ok},
     #test_case{module = "t7_SUITE",
       tc = "end_per_suite",
       tc_link = "t7_suite.end_per_suite.html",
       top_log = "t7_suite.end_per_suite.html#top",
       end_log = "t7_suite.end_per_suite.html#end",
       result = ok}];
expected_test_cases(t8_SUITE) ->
    [#test_case{module = "t8_SUITE",
       tc = "init_per_suite",
       tc_link = "t8_suite.init_per_suite.html",
       top_log = "t8_suite.init_per_suite.html#top",
       end_log = "t8_suite.init_per_suite.html#end",
       result = ok},
     #test_case{module = "t8_SUITE",
       group = "group1",
       tc = "init_per_group",
       tc_link = "t8_suite.init_per_group.html",
       top_log = "t8_suite.init_per_group.html#top",
       end_log = "t8_suite.init_per_group.html#end",
       result = ok},
     #test_case{module = "t8_SUITE",
       group = "subgroup1a",
       tc = "init_per_group",
       tc_link = "t8_suite.init_per_group.5826.html",
       top_log = "t8_suite.init_per_group.5826.html#top",
       end_log = "t8_suite.init_per_group.5826.html#end",
       result = ok},
     #test_case{num = 25,
       module = "t8_SUITE",
       group = "subgroup1a",
       tc = "test1a",
       tc_link = "t8_suite.test1a.html",
       top_log = "t8_suite.test1a.html#top",
       end_log = "t8_suite.test1a.html#end",
       result = skipped,
       comment = ["init_per_testcase failed"]},
     #test_case{num = 26,
       module = "t8_SUITE",
       group = "subgroup1a",
       tc = "test1b",
       tc_link = "t8_suite.test1b.html",
       top_log = "t8_suite.test1b.html#top",
       end_log = "t8_suite.test1b.html#end",
       result = ok},
     #test_case{module = "t8_SUITE",
       group = "subgroup1a",
       tc = "end_per_group",
       tc_link = "t8_suite.end_per_group.html",
       top_log = "t8_suite.end_per_group.html#top",
       end_log = "t8_suite.end_per_group.html#end",
       result = ok},
     #test_case{module = "t8_SUITE",
       group = "subgroup1b",
       tc = "init_per_group",
       tc_link = "t8_suite.init_per_group.5890.html",
       top_log = "t8_suite.init_per_group.5890.html#top",
       end_log = "t8_suite.init_per_group.5890.html#end",
       result = ok},
     #test_case{num = 27,
       module = "t8_SUITE",
       group = "subgroup1b",
       tc = "test1c",
       tc_link = "t8_suite.test1c.html",
       top_log = "t8_suite.test1c.html#top",
       end_log = "t8_suite.test1c.html#end",
       result = ok},
     #test_case{num = 28,
       module = "t8_SUITE",
       group = "subgroup1b",
       tc = "test1d",
       tc_link = "t8_suite.test1d.html",
       top_log = "t8_suite.test1d.html#top",
       end_log = "t8_suite.test1d.html#end",
       result = ok},
     #test_case{module = "t8_SUITE",
       group = "subgroup1b",
       tc = "end_per_group",
       tc_link = "t8_suite.end_per_group.5954.html",
       top_log = "t8_suite.end_per_group.5954.html#top",
       end_log = "t8_suite.end_per_group.5954.html#end",
       result = ok},
     #test_case{module = "t8_SUITE",
       group = "group1",
       tc = "end_per_group",
       tc_link = "t8_suite.end_per_group.6018.html",
       top_log = "t8_suite.end_per_group.6018.html#top",
       end_log = "t8_suite.end_per_group.6018.html#end",
       result = ok},
     #test_case{module = "t8_SUITE",
       group = "group2",
       tc = "init_per_group",
       tc_link = "t8_suite.init_per_group.6082.html",
       top_log = "t8_suite.init_per_group.6082.html#top",
       end_log = "t8_suite.init_per_group.6082.html#end",
       result = ok},
     #test_case{module = "t8_SUITE",
       group = "subgroup2a",
       tc = "init_per_group",
       tc_link = "t8_suite.init_per_group.6146.html",
       top_log = "t8_suite.init_per_group.6146.html#top",
       end_log = "t8_suite.init_per_group.6146.html#end",
       result = ok},
     #test_case{num = 29,
       module = "t8_SUITE",
       group = "subgroup2a",
       tc = "test2a",
       tc_link = "t8_suite.test2a.html",
       top_log = "t8_suite.test2a.html#top",
       end_log = "t8_suite.test2a.html#end",
       result = failed,
       comment = ["{t8_SUITE,test2a,<a href=\"t8_suite.src.html#42\">42</a>}",
       "{test2a_crash,[{t8_SUITE,...},{...}|...]}"]},
     #test_case{num = 30,
       module = "t8_SUITE",
       group = "subgroup2a",
       tc = "test2b",
       tc_link = "t8_suite.test2b.html",
       top_log = "t8_suite.test2b.html#top",
       end_log = "t8_suite.test2b.html#end",
       result = ok},
     #test_case{module = "t8_SUITE",
       group = "subgroup2a",
       tc = "end_per_group",
       tc_link = "t8_suite.end_per_group.6210.html",
       top_log = "t8_suite.end_per_group.6210.html#top",
       end_log = "t8_suite.end_per_group.6210.html#end",
       result = ok},
     #test_case{module = "t8_SUITE",
       group = "subgroup2b",
       tc = "init_per_group",
       tc_link = "t8_suite.init_per_group.6274.html",
       top_log = "t8_suite.init_per_group.6274.html#top",
       end_log = "t8_suite.init_per_group.6274.html#end",
       result = ok},
     #test_case{num = 31,
       module = "t8_SUITE",
       group = "subgroup2b",
       tc = "test2c",
       tc_link = "t8_suite.test2c.html",
       top_log = "t8_suite.test2c.html#top",
       end_log = "t8_suite.test2c.html#end",
       result = ok},
     #test_case{num = 32,
       module = "t8_SUITE",
       group = "subgroup2b",
       tc = "test2d",
       tc_link = "t8_suite.test2d.html",
       top_log = "t8_suite.test2d.html#top",
       end_log = "t8_suite.test2d.html#end",
       result = ok},
     #test_case{module = "t8_SUITE",
       group = "subgroup2b",
       tc = "end_per_group",
       tc_link = "t8_suite.end_per_group.6338.html",
       top_log = "t8_suite.end_per_group.6338.html#top",
       end_log = "t8_suite.end_per_group.6338.html#end",
       result = ok},
     #test_case{module = "t8_SUITE",
       group = "group2",
       tc = "end_per_group",
       tc_link = "t8_suite.end_per_group.6402.html",
       top_log = "t8_suite.end_per_group.6402.html#top",
       end_log = "t8_suite.end_per_group.6402.html#end",
       result = ok},
     #test_case{module = "t8_SUITE",
       tc = "end_per_suite",
       tc_link = "t8_suite.end_per_suite.html",
       top_log = "t8_suite.end_per_suite.html#top",
       end_log = "t8_suite.end_per_suite.html#end",
       result = ok}].
