#!/bin/sh
# %CopyrightBegin%
#
# SPDX-License-Identifier: Apache-2.0
#
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# %CopyrightEnd%

# ./create-image openssh 7.3p1 openssl 1.0.2m [in-file]
# ./create-image dropbear 2025.88 [in-file]

case $1 in
    openssh)
	FAMssh=openssh
	VERssh=$2
	FAMssl=$3
	VERssl=$4
	INPUT_FILE=$5
	VER=${FAMssh}${VERssh}-${FAMssl}${VERssl}
	FROM=ssh_compat_suite-${FAMssl}:${VERssl}
	PFX=https://ftp.eu.openbsd.org/pub/OpenBSD/OpenSSH/portable/openssh-
	SFX=.tar.gz
	TMP=tmp.tar.gz
	CONFIGURE_OPTS="--with-ssl-dir=/buildroot/ssl --with-pam"
	AFTER_CMD="RUN  echo UsePAM yes >> /buildroot/ssh/etc/sshd_config"
	CMD="/buildroot/ssh/sbin/sshd -D -p 1234"
	;;
    dropbear)
	FAMssh=dropbear
	VERssh=$2
	INPUT_FILE=$3
	VER=${FAMssh}${VERssh}
	FROM=ssh_compat_suite-ubuntu:latest
	PFX=https://matt.ucc.asn.au/dropbear/releases/dropbear-
	SFX=.tar.bz2
	TMP=tmp.tar.bz2
	CONFIGURE_OPTS="--enable-pam"
	AFTER_CMD="RUN  mkdir -p /etc/dropbear"
	# CMD="/bin/bash"
	CMD="/buildroot/ssh/sbin/dropbear -R -F -p 1234"
	;;
    *)
	echo "Unsupported: $1"
	exit
esac

# This way of fetching the tar-file separate from the docker commands makes
# http-proxy handling way easier. The wget command handles the $https_proxy
# variable while the docker command must have /etc/docker/something changed
# and the docker server restarted. That is not possible without root access.

# Make a Dockerfile. This method simplifies env variable handling considerably:
cat - > TempDockerFile <<EOF

    FROM  ${FROM}

    LABEL ${FAMssh}-version=${VER}

    WORKDIR /buildroot

    COPY ${TMP} .
    RUN  tar xf ${TMP}

    # Build and install

    WORKDIR ${FAMssh}-${VERssh}

    # Probably VERY OpenSSH dependent...:
    RUN ./configure --without-pie \
                    --prefix=/buildroot/ssh \
                    ${CONFIGURE_OPTS} \
                    LDFLAGS=-Wl,-R/buildroot/ssl/lib
    RUN  make
    RUN  make install
    ${AFTER_CMD}

    RUN echo Built ${VER}

    # Start the daemon, but keep it in foreground to avoid killing the container
    CMD ${CMD}

EOF

# Fetch the tar file. This could be done in an "ADD ..." in the Dockerfile,
# but then we hit the proxy problem...

if [ "x$INPUT_FILE" = "x" ]
then
    wget -O $TMP $PFX$VERssh$SFX

elif [ "x$INPUT_FILE" != "x$TMP" ]
then
    echo "Use $INPUT_FILE for input"
    cp $INPUT_FILE $TMP
fi

# Build the image:
docker build -t  ssh_compat_suite-ssh:$VER -f ./TempDockerFile .

# Cleaning
rm -fr ./TempDockerFile $TMP

